routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
*/

Route::get('/dashboard', function(){
    return redirect(route('companies.index'));
});

Route::prefix('dashboard')->group(function () {
    Route::resource('companies', 'Admin\CompanyController');
    Route::resource('coupons', 'Admin\CouponController');
});



// Route::get('/dashboard/companies', function(){
//     $companies = App\Company::all();
//     return view('dashboard.companies', compact('companies'));
// })->name('dashboard.companies');

// Route::get('/dashboard/company/{id}', function($id){
//     $company = App\Company::find($id);
//     return view('dashboard.company', compact('company'));
// })->name('dashboard.company');

// Route::get('/dashboard/coupon/{id}', function($id){
//     $coupon = App\Coupon::find($id);
//     return view('dashboard.coupon', compact('coupon'));
// })->name('dashboard.coupon');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();



Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/submit', 'HomeController@submit')->name('submit');

Route::get('/company/{id}', 'CompanyController@show')->name('company');

// Route::get('/test', function(){
//     return view('frontend.modal');
// });

use Spatie\SchemaOrg\Schema;

Route::get('/schema', function(){

    // load custom values for Q&A section
    FAQ::loadCustomValues([
        '{{COMPANY_NAME}}' => 'blabal',
        '{{NEW_COUPON_EVERY_X_DAYS}}' => 4,
        '{{LAST_X_DAYS}}' => 30,
        '{{NEW_COUPONS_COUNT_IN_LAST_X_DAYS}}' => 7,
        '{{MOST_POPULAIR_COUPON_TITLE}}' => 'Blabkads ysa dhuia',
        '{{USERS_SAVE_ON_AVERAGE_X}}' => 56.89
    ]);

    // try to render custom values into the Q&A's
    if($QnA = FAQ::compose()){

    }

    // $faq_schema = Schema::FAQPage()
    // ->mainEntity([
    //     Schema::Question()
    //     ->name('How often does Sakara release new coupon codes?')
    //     ->acceptedAnswer(
    //         Schema::Answer()->text("Lately we've discovered a new discount code from Sakara every 4 days. Over the last 30 days we've found 7 new coupons from Sakara.")
    //     ),
    //     Schema::Question()
    //     ->name('How much can I save by using a coupon at Sakara?')
    //     ->acceptedAnswer(
    //         Schema::Answer()->text("The best discount we've found is a code for 25% off. Wethrift shoppers save an average of $55.83 at checkout.")
    //     ),
    //     Schema::Question()
    //     ->name('How much can I save by using a coupon at Sakara?')
    //     ->acceptedAnswer(
    //         Schema::Answer()->text("The best discount we've found is a code for 25% off. Wethrift shoppers save an average of $55.83 at checkout.")
    //     )
    // ]);

    dd($faq_schema->toScript());
    
});

resources/views/dashboard/companies.blade.php
@extends('dashboard.layouts.app')

@section('content')

        <!-- Begin Page Content -->
        <div class="container-fluid">

            <!-- Page Heading -->
            <h1 class="h3 mb-2 text-gray-800">Companies</h1>
            <p class="mb-4">Bekijk en edit hier de bedrijven.</p>
  
            <!-- DataTales Example -->
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Companies</h6>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                      <tr>
                        <th>Edit</th>
                        <th>On top</th>
                        <th>Name</th>
                        <th>Url</th>
                        <th>About</th>
                        <th>Free returns</th>
                        <th>Free schipping</th>
                        <th>International schipping</th>
                        <th>Average saving</th>
                        <th>Available coupons</th>
                        <th>New coupons</th>
                        <th>Created at</th>
                        <th>Updated at</th>
                      </tr>
                    </thead>
                    <tfoot>
                      <tr>
                        <th>Edit</th>
                        <th>On top</th>
                        <th>Name</th>
                        <th>Url</th>
                        <th>About</th>
                        <th>Free returns</th>
                        <th>Free schipping</th>
                        <th>International schipping</th>
                        <th>Average saving</th>
                        <th>Available coupons</th>
                        <th>New coupons</th>
                        <th>Created at</th>
                        <th>Updated at</th>
                      </tr>
                    </tfoot>
                    <tbody>
                        @forelse ($companies as $company)
                        <tr>
                            <td><a class="btn btn-primary btn-round" href="{{route('companies.show', $company->id)}}">edit</a></td>
                            <td>
                                @if($company->top_choice)<i class="fas fa-check"></i>@else - @endif
                            </td>
                            <td>{{$company->name}}</td>
                            <td>{{$company->url}}</td>
                            <td>{{ Str::limit($company->about, 50) }}</td>
                            <td>@if($company->free_returns)<i class="fas fa-check"></i>@else - @endif</td>
                            <td>@if($company->free_shipping)<i class="fas fa-check"></i>@else - @endif</td>
                            <td>@if($company->international_shipping)<i class="fas fa-check"></i>@else - @endif</td>
                            <td>{{$company->average_saving}}</td>
                            <td>{{count($company->coupons)}}</td>
                            <td>{{count($company->coupons()->where('status', \App\Coupon::STATUS_NEW)->get())}}</td>
                            <td>{{$company->created_at}}</td>
                            <td>{{$company->updated_at}}</td>
                        </tr>
                        @empty
                            {{-- No companies --}}
                        @endforelse
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
  
          </div>
          <!-- /.container-fluid -->

      @endsection

resources/views/dashboard/company.blade.php
@extends('dashboard.layouts.app')

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
          @if ($errors->any())
          <div class="alert alert-danger" role="alert">
            <ul>
              @foreach ($errors->all() as $error)
                  <li>{{$error}}</li>
              @endforeach
            </ul>
          </div>
          @endif
          
            <!-- Dropdown Card Example -->
            <div class="card shadow mb-4">
              <!-- Card Header - Dropdown -->
              <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <a href="{{ route('companies.index') }}" class="btn btn-primary">< Back</a> <h6 class="m-0 font-weight-bold text-primary">{{ $company->name }}</h6>
                <div class="dropdown no-arrow">
                  <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Dropdown Header:</div>
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </div>
              </div>
              <!-- Card Body -->
              <div class="card-body">

                <form method="POST" action="{{route('companies.update', $company->id)}}">
                  @csrf
                  <input name="_method" type="hidden" value="PUT">

                  {{-- Name and Url --}}
                  <div class="form-group  row">
                    <div class="col-lg-3">
                      <label for="name" class="col-form-label">Name</label>
                      <input type="text" class="form-control" id="name" name="name" value="{{$company->name}}">
                    </div>
                    <div class="col-lg-9">
                      <label for="url" class="col-form-label">Url</label>
                      <input type="text" class="form-control" id="url" name="url" value="{{$company->url}}">
                    </div>
                  </div>

                  {{-- About --}}
                  <div class="form-group  row">
                    <div class="col-lg-12">
                      <label for="about" class="col-form-label">About</label>
                      <textarea type="text" class="form-control" id="about" name="about">{{$company->about}}</textarea>
                    </div>
                  </div>

                  {{-- Average saving price --}}
                  <div class="form-group  row">
                    <div class="col-lg-4">
                      <label for="average_saving" class="col-form-label">Average saving, €</label>
                      <input type="number" placeholder="1.0" step="0.01" min="0" name="average_saving" id="average_saving" value="{{$company->average_saving}}">
                    </div>
                  </div>

                  {{-- Company facts: top_choice, free_returns, free_shipping, international_shipping --}}
                    <div class="form-check">
                      <input type="hidden" value="0" name="top_choice">
                      <input onclick="$(this).val(this.checked ? 1 : 0)" class="form-check-input" type="checkbox" value="{{$company->top_choice}}" name="top_choice" id="top_choice" @if($company->top_choice) checked @endif >
                      <label class="form-check-label" for="top_choice">
                        Top choice
                      </label>
                    </div>
                    <div class="form-check">
                      <input type="hidden" value="0" name="free_returns">
                      <input onclick="$(this).val(this.checked ? 1 : 0)" class="form-check-input" type="checkbox" value="{{$company->free_returns}}" name="free_returns" id="free_returns" @if($company->free_returns) checked @endif >
                      <label class="form-check-label" for="free_returns">
                        Free returns
                      </label>
                    </div>
                    <div class="form-check">
                      <input type="hidden" value="0" name="free_shipping">
                      <input onclick="$(this).val(this.checked ? 1 : 0)" class="form-check-input" type="checkbox" value="{{$company->free_shipping}}" name="free_shipping" id="free_shipping" @if($company->free_shipping) checked @endif>
                      <label class="form-check-label" for="free_shipping">
                        Free shipping
                      </label>
                    </div>
                    <div class="form-check">
                      <input type="hidden" value="0" name="international_shipping">
                      <input onclick="$(this).val(this.checked ? 1 : 0)" class="form-check-input" type="checkbox" value="{{$company->international_shipping}}" name="international_shipping" id="international_shipping" @if($company->international_shipping) checked @endif>
                      <label class="form-check-label" for="international_shipping">
                        International shipping
                      </label>
                    </div>
                    <hr>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>

                <hr>

                <h1>Coupons</h1>
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                      <thead>
                        <tr>
                          <th>Edit</th>
                          <th>On top</th>
                          <th>Title</th>
                          <th>Code</th>
                          <th>Status</th>
                          <th>Used</th>
                          <th>Last used</th>
                          <th>Success rate</th>
                          <th>Created at</th>
                          <th>Updated at</th>
                        </tr>
                      </thead>
                      <tfoot>
                        <tr>
                          <th>Edit</th>
                          <th>On top</th>
                          <th>Title</th>
                          <th>Code</th>
                          <th>Status</th>
                          <th>Used</th>
                          <th>Last used</th>
                          <th>Success rate</th>
                          <th>Created at</th>
                          <th>Updated at</th>
                        </tr>
                      </tfoot>
                      <tbody>
                        @forelse ($company->coupons as $coupon)
                        <tr>
                          <td><a class="btn btn-primary btn-round" href="{{route('coupons.show', $coupon->id)}}">edit</a></td>
                          <td>
                              @if($coupon->top_choice)<i class="fas fa-check"></i>@else - @endif
                          </td>
                          <td>{{$coupon->title}}</td>
                          <td>{{$coupon->code}}</td>
                          <td>{{$coupon->humanStatus}}</td>
                          <td>{{$coupon->used}}</td>
                          <td>{{$coupon->last_used}}</td>
                          <td>%{{$coupon->success_rate}}</td>
                          <td>{{$coupon->created_at}}</td>
                          <td>{{$coupon->updated_at}}</td>
                        </tr>
                        @empty
                            {{-- No coupons --}}
                        @endforelse
                        
                      </tbody>
                    </table>
                  </div>
            </div>
              
            </div>
    </div>
</div>

@endsection

resources/views/dashboard/coupon.blade.php
@extends('dashboard.layouts.app')

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
          @if ($errors->any())
          <div class="alert alert-danger" role="alert">
            <ul>
              @foreach ($errors->all() as $error)
                  <li>{{$error}}</li>
              @endforeach
            </ul>
          </div>
          @endif

            <!-- Dropdown Card Example -->
            <div class="card shadow mb-4">
              <!-- Card Header - Dropdown -->
              <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
              <a href="{{ url()->previous() }}" class="btn btn-primary">< Back</a> <h6 class="m-0 font-weight-bold text-primary">Coupon</h6>
                <div class="dropdown no-arrow">
                  <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Dropdown Header:</div>
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </div>
              </div>
              <!-- Card Body -->
              <div class="card-body">



                {{-- FORM --}}

                <form method="POST" action="{{route('coupons.update', $coupon->id)}}">
                  @csrf
                  <input name="_method" type="hidden" value="PUT">

                  {{-- Name and Url --}}
                  <div class="form-group  row">
                    <div class="col-lg-3">
                      <label for="title" class="col-form-label">Title</label>
                      <input type="text" class="form-control" id="title" name="title" value="{{$coupon->title}}">
                    </div>
                    <div class="col-lg-9">
                      <label for="code" class="col-form-label">Code</label>
                      <input type="text" class="form-control" id="code" name="code" value="{{$coupon->code}}">
                    </div>
                  </div>

                  {{-- About --}}
                  <div class="form-group  row">
                    <div class="col-auto my-1">
                      <label class="mr-sm-2" for="status">Status</label>
                      <select name="status" class="custom-select mr-sm-2" id="status" >
                        <option value="10" @if($coupon->status == 10) selected @endif >Nieuw</option>
                        <option value="20" @if($coupon->status == 20) selected @endif>Geverifieerd</option>
                        <option value="30" @if($coupon->status == 30) selected @endif>Oud</option>
                        <option value="40" @if($coupon->status == 40) selected @endif>Verlopen</option>                    
                      </select>
                    </div>
                  </div>

                  {{-- used coupons count & success rate percentage --}}
                  <div class="form-group  row">
                    <div class="col-lg-4">
                      <label for="used" class="col-form-label">Used</label>
                      <input type="number" class="form-control" id="used" name="used" value="{{$coupon->used}}">
                    </div>
                    <div class="col-lg-4">
                      <label for="success_rate" class="col-form-label">Success rate, %</label>
                      <input type="number" class="form-control" id="success_rate" name="success_rate" value="{{$coupon->success_rate}}">
                    </div>
                  </div>


                  {{-- top_choice --}}
                  <div class="form-check">
                    <input type="hidden" value="0" name="top_choice">
                    <input onclick="$(this).val(this.checked ? 1 : 0)" class="form-check-input" type="checkbox" value="{{$coupon->top_choice}}" name="top_choice" id="top_choice" @if($coupon->top_choice) checked @endif >
                    <label class="form-check-label" for="top_choice">
                      Top choice
                    </label>
                  </div>

                  <hr>

                  <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
              
        </div>
    </div>
</div>

@endsection